api = "0.10"

[buildpack]
id = "mwacker-sms/apt"
version = "0.2.6"
name = "apt Packages Buildpack"
homepage = "https://github.com/mwacker-sms/apt-buildpack"
description = "Installs apt packages for further builds and runtime"
keywords = ["apt", "packages", "ubuntu"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.buildpacks.stacks.jammy"
