name: Release
on:
  release:
    types:
      - published
jobs:
  register:
    name: Package, Publish, and Register
    runs-on:
        - ubuntu-latest
    steps:
        - id: checkout
          name: Checkout code
          uses: actions/checkout@v4
        - if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
          name: Login to GitHub Package Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - id: setup-pack
          uses: buildpacks/github-actions/setup-pack@v5.5.4
        - id: package
          run: |
            #!/usr/bin/env bash
            set -euo pipefail
            BP_ID="$(cat buildpack.toml | yj -t | jq -r .buildpack.id)"
            VERSION="$(cat buildpack.toml | yj -t | jq -r .buildpack.version)"
            PACKAGE="${REPO}/$(echo "$BP_ID" | sed 's/\//_/g')"
            pack buildpack package --publish ${PACKAGE}:${VERSION}
            DIGEST="$(crane digest ${PACKAGE}:${VERSION})"
            echo "::set-output name=bp_id::$BP_ID"
            echo "::set-output name=version::$VERSION"
            echo "::set-output name=address::${PACKAGE}@${DIGEST}"
          shell: bash
          env:
            REPO: ghcr.io/${{ github.repository_owner }}/buildpacks
        - id: register
          uses: docker://ghcr.io/buildpacks/actions/registry/request-add-entry:5.5.0
          with:
            token:   ${{ secrets.GITHUB_TOKEN }}
            id:      ${{ steps.package.outputs.bp_id }}
            version: ${{ steps.package.outputs.version }}
            address: ${{ steps.package.outputs.address }}
